### PR TITLE
Specify which channels to read from BDF

### PR DESCRIPTION
**Pull request by codles**
This allows the user to specify which channels to import. This can reduce memory requirements and computation time.

For example reading a 262 MB file with all vs 3 channels:
```julia
using BDF, Benchmarks

origFilePath = "Example.bdf"

dats, evtTab, trigs, statusChan = readBDF(origFilePath)
dats, evtTab, trigs, statusChan = readBDF(origFilePath, channels = ["Cz", "P3", "T8"])

p = @benchmark readBDF(origFilePath); println(p)
p = @benchmark readBDF(origFilePath, channels = ["Cz", "P3", "T8"]); println(p)
```

Reading all channels
```
================ Benchmark Results ========================
     Time per evaluation: 937.03 ms [883.01 ms, 991.06 ms]
Proportion of time in GC: 6.86% [2.51%, 11.21%]
        Memory allocated: 916.65 mb
   Number of allocations: 5071 allocations
       Number of samples: 9
   Number of evaluations: 9
 Time spent benchmarking: 9.75 s
```

Reading three channels
```
================ Benchmark Results ========================
     Time per evaluation: 232.54 ms [224.39 ms, 240.70 ms]
Proportion of time in GC: 10.59% [8.63%, 12.55%]
        Memory allocated: 291.57 mb
   Number of allocations: 8950 allocations
       Number of samples: 47
   Number of evaluations: 47
 Time spent benchmarking: 11.54 s
```

### CODE REVIEW

**Comment by codles** [comment]
Also added an option to return the data transposed. This is useful as julia is not memory efficient for matrix transposes. This method takes the same memory regardless of transposing. 

```julia
dats, evtTab, trigs, statusChan = readBDF(origFilePath)
dats, evtTab, trigs, statusChan = readBDF(origFilePath, transposedata = true)

function nieve_t()
    dats, evtTab, trigs, statusChan = readBDF(origFilePath)
    return dats'
end
nieve_t()

p = @benchmark readBDF(origFilePath); println(p)
p = @benchmark readBDF(origFilePath, transposedata = true); println(p)
p = @benchmark nieve_t(); println(p)
```

Usual method
```
================ Benchmark Results ========================
     Time per evaluation: 947.92 ms [890.76 ms, 1.01 s]
Proportion of time in GC: 7.09% [2.36%, 11.82%]
        Memory allocated: 916.65 mb
   Number of allocations: 5071 allocations
       Number of samples: 9
   Number of evaluations: 9
 Time spent benchmarking: 9.70 s
```

New transpose method
```
================ Benchmark Results ========================
     Time per evaluation: 947.10 ms [864.24 ms, 1.03 s]
Proportion of time in GC: 8.01% [3.29%, 12.74%]
        Memory allocated: 916.65 mb
   Number of allocations: 5072 allocations
       Number of samples: 9
   Number of evaluations: 9
 Time spent benchmarking: 9.71 s
```

Nieve method
```
================ Benchmark Results ========================
     Time per evaluation: 1.36 s [1.24 s, 1.48 s]
Proportion of time in GC: 5.21% [0.00%, 12.08%]
        Memory allocated: 1.22 gb
   Number of allocations: 5075 allocations
       Number of samples: 6
   Number of evaluations: 6
 Time spent benchmarking: 9.92 s
```

**Comment by sam81** [comment]
Hi Rob, many thanks for the additional options. Before I merge the pull request I think it would be good to make the following minor changes:

- move the `if transposedata` before the `for` loops starts, so that the condition gets tested only once instead of being tested at each cycle of the loops. In other words, I think it would be better to have:

``` 
if transposedata
   for n=1:recordsToRead
      for c=1:nChannels
         # code not shown...
          for s=1:nSampRec
          end
      end
   end
else
   for n=1:recordsToRead
      for c=1:nChannels
         # code not shown...
          for s=1:nSampRec
          end
      end
   end
end
   
- change all argument names to camel case (`fname` to `fName`, `transposedata` to `transposeData`, etc...). Also I find it easier to read variable names in came case (e.g. change `cidx` to `cIdx`.

- on line 36 you specify `channels::AbstractArray=[0]`, would it be possible to use `channels::AbstractVector=[0]` instead? `AbstractArray` seems to imply that the argument could be a matrix. Also, for consistency with the way the default `to` argument is given, it would be better to use  `channels::AbstractVector=[-1]` for the case in which the use wants all channels.

Just out of curiosity, do you have a specific use case for having the data matrix transposed?

Cheers,

Sam

**Comment by codles** [comment]
Thanks for the feedback. Let me know if you want any other changes made.

**Comment by codles** [comment]
Regarding the use case for the data matrix. When I started using Julia I found that fft along the first dimension is faster, so I preferred having the channels on the last dimension. Eg

```julia

println(@benchmark(fft(rand(8192*10, 64), 1)))
================ Benchmark Results ========================
     Time per evaluation: 1.02 s [844.62 ms, 1.20 s]
Proportion of time in GC: 1.32% [0.00%, 3.21%]
        Memory allocated: 160.00 mb
   Number of allocations: 68 allocations
       Number of samples: 9
   Number of evaluations: 9
 Time spent benchmarking: 10.46 s

println(@benchmark(fft(rand(64, 8192*10), 2)))
================ Benchmark Results ========================
     Time per evaluation: 2.01 s [1.67 s, 2.34 s]
Proportion of time in GC: 0.55% [0.00%, 2.30%]
        Memory allocated: 160.00 mb
   Number of allocations: 63 allocations
       Number of samples: 4
   Number of evaluations: 4
 Time spent benchmarking: 10.26 s
```

Now I mainly use rfft_plan, which is still faster along the first dimension

```julia

p = plan_rfft(rand(8192*10, 64), 1, flags = FFTW.MEASURE)
p * rand(8192*10, 64)
println(@benchmark(p * rand(8192*10, 64)))
================ Benchmark Results ========================
     Time per evaluation: 245.19 ms [225.71 ms, 264.66 ms]
Proportion of time in GC: 3.21% [1.84%, 4.58%]
        Memory allocated: 40.00 mb
   Number of allocations: 4 allocations
       Number of samples: 38
   Number of evaluations: 38
 Time spent benchmarking: 9.86 s

p = plan_rfft(rand(64, 8192*10), 2, flags = FFTW.MEASURE)
p * rand(64, 8192*10)
println(@benchmark(p * rand(64, 8192*10)))
================ Benchmark Results ========================
     Time per evaluation: 541.89 ms [484.58 ms, 599.20 ms]
Proportion of time in GC: 1.21% [0.00%, 2.44%]
        Memory allocated: 40.00 mb
   Number of allocations: 4 allocations
       Number of samples: 14
   Number of evaluations: 14
 Time spent benchmarking: 8.52 s
```

Is there a particular reason you returned the data the other way? For me it might have also been some left over matlabism.

**Comment by sam81** [comment]
many thanks, I've merged the pull request. Thanks for the info on FFT speed along different dimensions, that's good to know. As for the reason I originally chose to return the data as an nChannelsXnDataPoints matrix I can't remeber the exact reason. I think that EEGLAB returns data in the same way. Also, software to visualize the online EEG visually shows data in that way, so it's kind of natural to think of think of the data matrix as an nChannelsXnDataPoints matrix.

**Comment by codles** [comment]
Cheers

**Pull request merged**
