### PR TITLE
Switch to Project.toml from REQUIRE

### PR DESCRIPTION
**Pull request by rob-luke**
This allows the package to work with the latest Julia versions.

I appreciate this great package and would love to keep using it with latest Julia versions, thanks for considering this PR.

### CODE REVIEW

**Comment by sam81** [comment]
Hi Rob thank you for the PR, sorry for the long wait for merging. My interests are shifting away from research and I'm not sure to what extent I'll be able to maintain my code repositories. I've tried to add you as a collaborator so that you can have direct access to merge commits on this repo. Eventually I'd be happy for you to take over and maintain the repo if you'd be available for that.

**Comment by rob-luke** [comment]
Hi Sam, no worries on the delay, we all have other things going on, particularly these days.

> My interests are shifting away from research and I'm not sure to what extent I'll be able to maintain my code repositories

Good luck with the new adventure. I'd actually been hoping to meet you at ARO or some other auditory meeting (there aren't that many of us that study both ASSRs and use Julia). But in lieu of that, thanks for the great packages over the years.

> I've tried to add you as a collaborator so that you can have direct access to merge commits on this repo. Eventually I'd be happy for you to take over and maintain the repo if you'd be available for that.

I can confirm I have received the invite. I may switch to using https://github.com/beacon-biosignals/EDF.jl/pull/46 in the future, but for now I am happy to help you maintain this project. I can field small PRs etc.

Do you have plans to continue maintaining BrainWave.jl too? If not, would you be open to me integrating some of the code in to Neuroimaging.jl? I don't know about licenses etc, but let me know if you're open to the idea.

Again, good luck with the next chapter

**Comment by sam81** [comment]
Hi Rob, thank you for your availability to help maintain BDF. Yes, it's a shame we haven't had the opportunity to meet at a conference so far! Regarding BDF.jl, if you now have full commit access to the repo, feel free to directly merge the changes. I trust your judgement.

Brainwave.jl is in the same boat as BDF.jl, I don't have plans to continue developing it and I'll have progressively less time to maintain it. Most of the Brainwave.jl code performs basic, not particularly original, pre-processing tasks. I'd be happy for you to integrate it in Neuroimaging.jl. It's licenced under the MIT licence, so I suppose that you shouldn't have issues already doing that, but I'd be happy to change the licence to something more permissive if needed, just let me know. I'd be happier seeing at least some of the code I wrote adapted and re-used than die away into disuse.

**Comment by rob-luke** [comment]
> Regarding BDF.jl, if you now have full commit access to the repo, feel free to directly merge the changes. I trust your judgement.

Awesome, Ill just try and tag a new version then no other big changes planned. Thanks for the help.

> I'd be happier seeing at least some of the code I wrote adapted and re-used than die away into disuse.

I know that feeling, that's the main reason I decided to revamp EEG.jl as Neuroimaging.jl. I pumped lots of hours in to that and then it just fades away as versions change and the upkeep takes time. I will ping you if I integrate any of your code, but thanks in advance.

**Pull request merged**
